import { Schema, arrayOf } from 'normalizr';


export const ActionTypes = {
	FETCH_GAMES_REQUEST: 'FETCH_GAMES_REQUEST',
	FETCH_GAMES_SUCCESS: 'FETCH_GAMES_SUCCESS',
	FETCH_GAMES_FAILURE: 'FETCH_GAMES_FAILURE',

	TOGGLE_GAME_OWNERSHIP_REQUEST: 'TOGGLE_GAME_OWNERSHIP_REQUEST',
	TOGGLE_GAME_OWNERSHIP_SUCCESS: 'TOGGLE_GAME_OWNERSHIP_SUCCESS',
	TOGGLE_GAME_OWNERSHIP_FAILURE: 'TOGGLE_GAME_OWNERSHIP_FAILURE',

	TOGGLE_GAME_KNOWLEDGE_REQUEST: 'TOGGLE_GAME_KNOWLEDGE_REQUEST',
	TOGGLE_GAME_KNOWLEDGE_SUCCESS: 'TOGGLE_GAME_KNOWLEDGE_SUCCESS',
	TOGGLE_GAME_KNOWLEDGE_FAILURE: 'TOGGLE_GAME_KNOWLEDGE_FAILURE',

	AUTH_USER_REQUEST: 'AUTH_USER_REQUEST',
	AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
	AUTH_USER_FAILURE: 'AUTH_USER_FAILURE',
	AUTH_USER_LOGOUT: 'AUTH_USER_LOGOUT',

	PAGINATE_GAMES: 'PAGINATE_GAMES',
	FILTER_GAMES: 'FILTER_GAMES',
};


const user = new Schema('users');
const game = new Schema('games');
game.define({
	owners: arrayOf(user),
	knowers: arrayOf(user),
});

export const Schemas = {
	USER: user,
	GAME: game,
	GAMES: arrayOf(game),
}


const isTest = process.env.NODE_ENV === 'test';
export const API_ENDPOINT_URL = `${isTest ? 'http://localhost' : ''}/api`;

export const AUTH_HEADER_PREFIX = 'JWT ';

export const PER_PAGE = 20;