import { Schema, arrayOf } from 'normalizr';


export const ActionTypes = {
	FETCH_GAMES_REQUEST: 'FETCH_GAMES_REQUEST',
	FETCH_GAMES_SUCCESS: 'FETCH_GAMES_SUCCESS',
	FETCH_GAMES_FAILURE: 'FETCH_GAMES_FAILURE',

	TOGGLE_GAME_OWNERSHIP_REQUEST: 'TOGGLE_GAME_OWNERSHIP_REQUEST',
	TOGGLE_GAME_OWNERSHIP_SUCCESS: 'TOGGLE_GAME_OWNERSHIP_SUCCESS',
	TOGGLE_GAME_OWNERSHIP_FAILURE: 'TOGGLE_GAME_OWNERSHIP_FAILURE',

	TOGGLE_GAME_KNOWLEDGE_REQUEST: 'TOGGLE_GAME_KNOWLEDGE_REQUEST',
	TOGGLE_GAME_KNOWLEDGE_SUCCESS: 'TOGGLE_GAME_KNOWLEDGE_SUCCESS',
	TOGGLE_GAME_KNOWLEDGE_FAILURE: 'TOGGLE_GAME_KNOWLEDGE_FAILURE',

	AUTH_USER_REQUEST: 'AUTH_USER_REQUEST',
	AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
	AUTH_USER_FAILURE: 'AUTH_USER_FAILURE',
};


const game = new Schema('games');

export const Schemas = {
	GAME: game,
	GAMES: arrayOf(game),
	USER: new Schema('user'),
}

// todo this needs to go in a config file somewhere
export const API_ENDPOINT_URL = 'http://localhost:5000/api';
