# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'jeu', 'verbose_name_plural': 'jeux'},
        ),
        migrations.AlterModelOptions(
            name='knower',
            options={'verbose_name': 'connaisseur'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'propri\xe9taire'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'joueur'},
        ),
        migrations.AddField(
            model_name='owner',
            name='is_bringing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='knower',
            name='fk_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Jeu'),
        ),
        migrations.AlterField(
            model_name='knower',
            name='fk_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fk_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Jeu'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fk_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur'),
        ),
    ]
