# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170206_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
