# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170206_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_animajoueur',
            field=models.BooleanField(default=True, verbose_name='Animajoeur'),
        ),
    ]
