# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type_genre',
            field=models.TextField(db_column='type', default='Gestion', verbose_name='Type'),
        ),
    ]
