# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_user_is_animajoueur'),
        ('games', '0007_auto_20170319_1615'),
    ]

    operations = [
    ]
