# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_merge_20170415_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_bgg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id_bgg',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(unique=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type_genre',
            field=models.TextField(choices=[('Ambiance', 'Ambiance'), ('Coop\xe9ratif', 'Coop\xe9ratif'), ('Strat\xe9gie', 'Strat\xe9gie'), ('Placement', 'Placement'), ('Parcours', 'Parcours'), ('Gestion', 'Gestion'), ('Enfants', 'Enfants'), ('Ench\xe8res', 'Ench\xe8res')], db_column='type', default='Gestion', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_animajoueur',
            field=models.BooleanField(default=True, verbose_name='Animajoueur'),
        ),
    ]
