# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170415_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_bgg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
