# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20170415_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dur\xe9e'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age max.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_player',
            field=models.IntegerField(blank=True, null=True, verbose_name='Joueurs max.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age min.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_player',
            field=models.IntegerField(blank=True, null=True, verbose_name='Joueurs min.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type_genre',
            field=models.TextField(choices=[('Ambiance', 'Ambiance'), ('Coop\xe9ratif', 'Coop\xe9ratif'), ('Strat\xe9gie', 'Strat\xe9gie'), ('Placement', 'Placement'), ('Parcours', 'Parcours'), ('Gestion', 'Gestion'), ('Enfants', 'Enfants'), ('Ench\xe8res', 'Ench\xe8res')], db_column='type', default='Gestion', verbose_name='Genre'),
        ),
    ]
